// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function cardColor(c) {
  var match = c.suit;
  if (match === 2 || match === 1) {
    return /* Red */0;
  } else {
    return /* Black */1;
  }
}

function areCardsDifferentColor(c1, c2) {
  return cardColor(c1) !== cardColor(c2);
}

function areRanksInDescendingOrder(sourceCard, destinationCard) {
  return destinationCard.rank === (sourceCard.rank + 1 | 0);
}

function isLegalMove(sourceCard, destinationCard) {
  if (areCardsDifferentColor(sourceCard, destinationCard)) {
    return areRanksInDescendingOrder(sourceCard, destinationCard);
  } else {
    return false;
  }
}

exports.cardColor = cardColor;
exports.areCardsDifferentColor = areCardsDifferentColor;
exports.areRanksInDescendingOrder = areRanksInDescendingOrder;
exports.isLegalMove = isLegalMove;
/* No side effect */
