// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function areCardsDifferentColor(c1, c2) {
  return c1.suit !== c2.suit;
}

function areRanksInDescendingOrder(sourceCard, destinationCard) {
  return destinationCard.rank === (sourceCard.rank + 1 | 0);
}

function isLegalMove(sourceCard, destinationCard) {
  if (areCardsDifferentColor(sourceCard, destinationCard)) {
    return areRanksInDescendingOrder(sourceCard, destinationCard);
  } else {
    return false;
  }
}

exports.areCardsDifferentColor = areCardsDifferentColor;
exports.areRanksInDescendingOrder = areRanksInDescendingOrder;
exports.isLegalMove = isLegalMove;
/* No side effect */
