// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var TestLib$IneffectiveTests = require("./TestLib.bs.js");
var Freecell$IneffectiveTests = require("./Freecell.bs.js");

function testLegalityOfFiveOfSpadesAndSixOfHearts(param) {
  var fiveOfSpades = {
    suit: /* Spades */3,
    rank: 5
  };
  var sixOfHearts = {
    suit: /* Hearts */2,
    rank: 6
  };
  var isFiveToSixLegal = Freecell$IneffectiveTests.isLegalMove(fiveOfSpades, sixOfHearts);
  var isSixToFiveLegal = Freecell$IneffectiveTests.isLegalMove(sixOfHearts, fiveOfSpades);
  return /* :: */[
          TestLib$IneffectiveTests.Bool.assertEqual(true, isFiveToSixLegal, "Moving the five of spades onto the six of hearts is a legal move"),
          /* :: */[
            TestLib$IneffectiveTests.Bool.assertEqual(false, isSixToFiveLegal, "Moving the six of hearts onto the five of spades is not a legal move"),
            /* [] */0
          ]
        ];
}

function testLegalityOfFiveOfSpadesAndSixOfClubs(param) {
  var isFiveToSixLegal = Freecell$IneffectiveTests.isLegalMove({
        suit: /* Spades */3,
        rank: 5
      }, {
        suit: /* Clubs */0,
        rank: 6
      });
  return /* :: */[
          TestLib$IneffectiveTests.Bool.assertEqual(false, isFiveToSixLegal, "Moving the five of spades onto the six of spades is not a legal move"),
          /* [] */0
        ];
}

TestLib$IneffectiveTests.runSuite(/* :: */[
      testLegalityOfFiveOfSpadesAndSixOfHearts,
      /* :: */[
        testLegalityOfFiveOfSpadesAndSixOfClubs,
        /* [] */0
      ]
    ]);

exports.testLegalityOfFiveOfSpadesAndSixOfHearts = testLegalityOfFiveOfSpadesAndSixOfHearts;
exports.testLegalityOfFiveOfSpadesAndSixOfClubs = testLegalityOfFiveOfSpadesAndSixOfClubs;
/*  Not a pure module */
